CREATE DATABASE AB106Practise
USE AB106Practise

CREATE TABLE Students(
Id INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(25) NOT NULL,
Surname NVARCHAR(25) DEFAULT 'XXX',
Point TINYINT CHECK(Point BETWEEN 0 AND 100),
Email VARCHAR(256) UNIQUE
)

INSERT INTO Students VALUES(N'Əli',N'Şükürov',80,'ali@gmail.com')
